### PR TITLE
add some words

### PR DESCRIPTION
**Pull request by rbalet**
Some words found in an angular project

### CODE REVIEW

**Comment by Jason3S** [comment]
Thank you! Generally I like to do these as separate requests.

**Comment by rbalet** [comment]
Aïe, sorry. I realise that every push I've done had created a new pull request. My bad sry. By the way. I've created 2 new vscode plugin  (for Lorem and fullstack) how could I share this in a proper way?

**Comment by Jason3S** [comment]
I have been putting the extensions here: [Jason3S/vscode-cspell-dict-extensions: VS Code Spelling Dictionary Extensions](https://github.com/Jason3S/vscode-cspell-dict-extensions)

Would you please give me permissions to publish to npmjs Fullstack? That way it is possible for me to keep it up to date.

**Comment by Jason3S** [comment]
Just add [jason-dent](https://www.npmjs.com/~jason-dent) to [cspell-dict-fullstack - npm](https://www.npmjs.com/package/cspell-dict-fullstack). Under Admin there is the option to `Invite maintainer`

**Comment by rbalet** [comment]
- Invite maintainer:  It's done 
- vsce plugin: Uploaded and done a pull request. I hope it's how you want it.

I hope I done this in a proper way. If not let me know :)

**Pull request merged**
