### PR TITLE
Update dictionary, fix apostrophes

### PR DESCRIPTION
**Pull request by canarduck**
Here's an updated version of the French dictionary, the one you used from [titoBouzout/Dictionaries](https://github.com/titoBouzout/Dictionaries/blob/master/French.txt) was a bit old.
I've also added some rules to the ’ignoreRegExpList’ you introduced recently, this should fix all the false positives with French's _apostroph-ed_ words.

### CODE REVIEW

**Comment by Jason3S** [comment]
Awsome!

**Comment by Jason3S** [comment]
Did you see:
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french

I'll update it with your update!

**Comment by Jason3S** [comment]
Updated.

**Comment by canarduck** [comment]
This is great and so much easier than installing dictionaries from npm !

Btw looks like [you left hardcoded some "Spanish" in your Yeoman's templates](https://github.com/search?utf8=%E2%9C%93&q=spanish+repo%3AJason3S%2Fvscode-cspell-dict-extensions+path%3Agenerator-cspell-dicts-extensions%2Fgenerators%2Fapp%2Ftemplates&type=Code&ref=advsearch&l=&l=), for example [Manual settings](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french#manual-settings) in the README :

> Adding fr to the cSpell.language setting, will enable the **Spanish** dictionary.
Example using both English and French dictionaries:

**Comment by Jason3S** [comment]
Thank you!  I'll fix it.

Since you were opening .aff files:
[Aff syntax highlighter](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.hunspell)

**Pull request merged**
